In [1]:
import numpy as np 

In [2]:
control_points = np.load(
    'gripper_control_points/panda.npy'
)[:, :3]

In [4]:
control_points

array([[ 5.2687433e-02, -5.9955313e-05,  7.5273141e-02],
       [-5.2687433e-02,  5.9955313e-05,  7.5273141e-02],
       [ 5.2687433e-02, -5.9955313e-05,  7.8606479e-02],
       [-5.2687433e-02,  5.9955313e-05,  7.8606479e-02],
       [ 5.2687433e-02, -5.9955313e-05,  8.1939809e-02],
       [-5.2687433e-02,  5.9955313e-05,  8.1939809e-02],
       [ 5.2687433e-02, -5.9955313e-05,  8.5273139e-02],
       [-5.2687433e-02,  5.9955313e-05,  8.5273139e-02],
       [ 5.2687433e-02, -5.9955313e-05,  8.8606477e-02],
       [-5.2687433e-02,  5.9955313e-05,  8.8606477e-02],
       [ 5.2687433e-02, -5.9955313e-05,  9.1939807e-02],
       [-5.2687433e-02,  5.9955313e-05,  9.1939807e-02],
       [ 5.2687433e-02, -5.9955313e-05,  9.5273145e-02],
       [-5.2687433e-02,  5.9955313e-05,  9.5273145e-02],
       [ 5.2687433e-02, -5.9955313e-05,  9.8606475e-02],
       [-5.2687433e-02,  5.9955313e-05,  9.8606475e-02],
       [ 5.2687433e-02, -5.9955313e-05,  1.0193981e-01],
       [-5.2687433e-02,  5.9955

In [5]:
control_points = [[0, 0, 0], control_points[0, :], control_points[1, :], control_points[-2, :], control_points[-1, :]]

In [6]:
control_points

[[0, 0, 0],
 array([ 5.2687433e-02, -5.9955313e-05,  7.5273141e-02], dtype=float32),
 array([-5.2687433e-02,  5.9955313e-05,  7.5273141e-02], dtype=float32),
 array([ 5.2687433e-02, -5.9955313e-05,  1.0527314e-01], dtype=float32),
 array([-5.2687433e-02,  5.9955313e-05,  1.0527314e-01], dtype=float32)]